name: Flutter Build and Release

on:
  push:
    tags:
      - 'release-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/release-}" >> $GITHUB_ENV
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-stable'

      - name: Get dependencies
        run: |
          cd b_winter
          flutter pub get

      - name: Build APK
        run: |
          cd b_winter
          flutter build apk --flavor githubRelease --release

      - name: List built APK files
        run: |
          cd b_winter
          find build/app/outputs/flutter-apk/ -name "*.apk" -type f
          ls -la build/app/outputs/flutter-apk/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: b_winter/build/app/outputs/flutter-apk/*.apk
          name: Release ${{ env.VERSION }}
          tag_name: ${{ github.ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fail_on_unmatched_files: false
